on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test of my action 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test my action - expect image to exist
        id: test-exists
        uses: ./
        with:
          region: ap-northeast-1
          repository-name: ${{ secrets.ECR_REPOSITORY_NAME }}
          image-tag: ${{ secrets.IMAGE_TAG }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get the output
        run: echo "image-exists=${{ steps.test-exists.outputs.image-exists }}"

      - name: test my action - expect image not to exist
        id: test-doesnt-exist
        uses: ./
        with:
          region: ap-northeast-1
          repository-name: ${{ secrets.ECR_REPOSITORY_NAME }}
          image-tag: "dummy"
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get the output
        run: echo "image-exists=${{ steps.test-doesnt-exist.outputs.image-exists }}"
